### ISSUE TITLE
Install doesn't work

### ISSUE THREAD

**Issue by nedzen** [B3nnyL/figgo#21]
I installed and reinstalled node 2 times, running `node version 12.13.0` 

```
❯ npm i figgo -g
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /usr/local/lib/node_modules/figgo/dist/cli.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/figgo/dist/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mariusnedelcu/.npm/_logs/2019-10-31T09_22_33_609Z-debug.log
```

Can anyone please tell me what is going on here ?

is this related to the plugin or to my environment ?

**Comment by B3nnyL** [comment]
Hmm... checking. Thanks for reporting @nedzen

**Comment by nedzen** [comment]
I actually installed a previous version `figgo@0.1.11` and works like a charm :)

**Comment by B3nnyL** [comment]
@nedzen I forgot to publish build to npm... It should be ok now, try `npm i figgo@0.2.3 -g`.
