### ISSUE TITLE
Output format CSS

### ISSUE THREAD

**Issue by felixdorner** [B3nnyL/figgo#6]
Great tool! Do you plan by any chance a plain CSS output with custom properties (CSS variables)?

**Comment by B3nnyL** [comment]
Thanks foe bring it up! Yes, exporting css is on Figgo's roadmap, I'll keep you update when it's ready. Cheers 😊

**Comment by leereichardt** [comment]
Hi,

Any idea on when this enhancement might happen?

**Comment by B3nnyL** [comment]
Hi @leereichardt , CSS variable is supported in v.0.2.x #17 . Welcome to share your feedback :)
