### ISSUE TITLE
Different Hex Color Output

### ISSUE THREAD

**Issue by ChandanMahapatra** [B3nnyL/figgo#7]
My hex color output seems to be different from the one in Figma.

SCSS File = #ec5858;
Figma = #EB5757

![test1](https://user-images.githubusercontent.com/14539609/56685542-0579d780-6687-11e9-9c3f-714272a97633.png)

![test](https://user-images.githubusercontent.com/14539609/56685338-8f757080-6686-11e9-883c-15c2b80d33e6.png)

**Comment by B3nnyL** [comment]
@ChandanMahapatra Thanks for reporting, I'll fix it soon

**Comment by ChandanMahapatra** [comment]
@B3nnyL Thanks for making figgo, it's really easy to use and helpful 😄

**Comment by sogen** [comment]
happens as well in `colorToken.js` file

**Comment by ssi-kevin-muldoon** [comment]
Hey guys! Love the tool. Wanted to report same bug. SCSS = #3FA9DE where FIGMA = #3EA8DD

**Comment by ssi-kevin-muldoon** [comment]
Also, see about adding the ALPHA value into HEX as well. Very helpful info.

**Comment by B3nnyL** [comment]
fix #23
